#ifndef SERVERCONFIG_HPP
#define SERVERCONFIG_HPP

#define SERVER_PORT 12412
#define MESSAGE_MAX_SIZE 4096
#define MESSAGE_END_STRING "\r\n\r\n\r\n"
#define MESSAGE_END_SIZE sizeof(MESSAGE_END_STRING)

#endif // SERVERCONFIG_HPP
